name: Manual Version Trigger Workflow

on:
  workflow_dispatch:

jobs:
  manual-trigger:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest release
        id: get_latest_release
        shell: cmd
        run: |
          echo Fetching latest release from the GitHub API...
          for /f "tokens=1,2 delims=," %%A in ('curl -s "https://api.github.com/repos/%GITHUB_REPOSITORY%/releases/latest" ^| jq -r ".tag_name, .target_commitish"') do (
            set "latest_release=%%A"
            set "target_commit=%%B"
          )
          if "%latest_release%"=="" (
            echo No previous release found. Defaulting to v1.0.0.
            echo version=v1.0.0 >> %GITHUB_ENV%
            echo last_commit= >> %GITHUB_ENV%
          ) else (
            echo Latest tag: %latest_release%
            echo Last commit hash: %target_commit%
            echo version=%latest_release% >> %GITHUB_ENV%
            echo last_commit=%target_commit% >> %GITHUB_ENV%
          )

      - name: Increment version
        id: increment_version
        shell: cmd
        run: |
          echo Incrementing version...
          set "latest_version=%version%"
          for /f "tokens=1,2,3 delims=." %%A in ("%latest_version:v=%") do (
            set "major=%%A"
            set "minor=%%B"
            set "patch=%%C"
          )
          if "%patch%"=="" set patch=0
          set /a new_patch=%patch% + 1
          set "new_version=v%major%.%minor%.%new_patch%"
          echo New version: %new_version%
          echo new_version=%new_version% >> %GITHUB_ENV%

      - name: Install dependencies
        shell: cmd
        run: |
          python -m pip install -r requirements.txt
          python -m pip install nuitka

      - name: